#!/bin/bash

for ip in `cat printerip`
do
	printername=`snmpwalk -c public -v 2c "$ip" HOST-RESOURCES-MIB::hrDeviceDescr.1 | sed 's/^.*: //'`
 
#	echo $ip
#	echo "$printername"

if [[ $printername == *P3010* ]]; then
	tray1=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.1.0 | sed 's/^.*: //'`
	tray2=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.2.0 | sed 's/^.*: //'`
	tray3=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.3.0 | sed 's/^.*: //'`	
	tray4=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.4.0 | sed 's/^.*: //'`

	echo ""
	echo "Printer $ip - $printername"	

	echo "Tray 1 usage - $tray1"
	echo "Tray 2 usage - $tray2"
	if [[ $tray3 != *OID* ]]; then echo "Tray 3 usage - $tray3"; fi
	if [[ $tray4 != *OID* ]]; then echo "Tray 4 usage - $tray4"; fi


elif [[ $printername == *P4515* ]] || [[ $printername == *P3005* ]] || [[ $printername == *4250* ]] || [[ $printername == *4015* ]]; then
	tray1=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.3.0 | sed 's/^.*: //'`
	tray2=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.4.0 | sed 's/^.*: //'`
	tray3=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.5.0 | sed 's/^.*: //'`
	tray4=`snmpwalk -c public -v 2c $ip enterprises.11.2.3.9.4.2.1.1.16.5.1.1.7.0 | sed 's/^.*: //'`
	echo ""
	echo "Printer $ip - $printername"
        echo "Tray 1 usage - $tray1"
        echo "Tray 2 usage - $tray2"
        echo "Tray 3 usage - $tray3"
        echo "Tray 4 usage - $tray4"

else
	
	echo ""
	echo "not a supported printer -- $ip - $printername"

fi

done

